# SPDX-FileCopyrightText: TNG Technology Consulting GmbH
#
# SPDX-License-Identifier: Apache-2.0

# insert the name of your tool here to identify its run in GitHub actions
name: "Testcases for tools-java"

on:
  workflow_dispatch:

jobs:
  run-testcases:
    name: "Run Testcases"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
      
      # user tool specific section starts here

      - name: Download spdx-tools-java-solver fat jar
        id: download-spdx-tools-java-solver-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci-cd-tools-java-solver.yaml
          branch: main
          name: tools-java-solver-artifact

      - name: Run spdx-tools-java-solver to create input file
        id: generate-input
        run: |
          java -jar spdx-tools-java-solver-*-all.jar -t generationMinimalTest -f generationMinimal.xml
          java -jar spdx-tools-java-solver-*-all.jar -t generationBaselineSbomTest -f generationBaselineSbom.xml
          java -jar spdx-tools-java-solver-*-all.jar -t generationDocumentTest -f generationDocument.xml
          java -jar spdx-tools-java-solver-*-all.jar -t generationLicenseTest -f generationLicense.xml
          java -jar spdx-tools-java-solver-*-all.jar -t generationRelationshipTest -f generationRelationship.xml
      
      # user tool specific section ends here

      - name: Download testbed fat jar
        id: download-testbed-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci-cd-testbed.yaml
          branch: master
          name: testbed-artifact

      - name: Run test case
        # provide the -t flag with the name of the test case that the input file (-f) attempts to solve
        # look up the README for a list of possible test case names
        run: |
          java -jar testbed-*-all.jar -t generationMinimalTest -f generationMinimal.xml
          java -jar testbed-*-all.jar -t generationBaselineSbomTest -f generationBaselineSbom.xml
          java -jar testbed-*-all.jar -t generationDocumentTest -f generationDocument.xml
          java -jar testbed-*-all.jar -t generationLicenseTest -f generationLicense.xml
          java -jar testbed-*-all.jar -t generationRelationshipTest -f generationRelationship.xml
